### ISSUE TITLE
Make it usable with parcel nightlies

### ISSUE THREAD

**Issue by folknor** [VladimirMikulic/parcel-resolver-ignore#10]
Hi,

Could you please change the `engines` requirements in package.json so that this plugin is usable with parcel nightlies?

Here's what happens now:
```

🚨 Build failed.

@parcel/core: The plugin "parcel-resolver-ignore" is not compatible with the current version of Parcel. Requires ">=2.0.0" but the current version is "2.0.0-nightly.1163+55140b640".

  /.../node_modules/.pnpm/parcel-resolver-ignore@2.1.3_parcel@2.0.0-nightly.1163/node_modules/parcel-resolver-ignore/package.json:7:5
    6 |   "engines": {
  > 7 |     "parcel": ">=2.0.0"
  >   |     ^^^^^^^^^^^^^^^^^^^
    8 |   },
    9 |   "keywords": [

 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

```

This is of course due to the semver nonsense. There are several tickets in the parcel repo related to their nightlies breaking because they didn't have versions that could be properly compared using semver. This was fixed by their build script manually adjusting all their package.jsons when releasing.

I'm sure you can find a version compare string that works. I'm just too tired now to think.

Thank you!

**Comment by VladimirMikulic** [comment]
Hi @folknor. Thanks for reaching out.
Could you please describe what usecase this would serve?
What makes you use/rely on nightly versions of Parcel?

**Comment by folknor** [comment]
I no longer have a usecase for using nightlies. For years they were working on 2.0 without releasing, and during that time I was using them.

In any case even when I manually changed the engines field in your package.json it didn't stop the default resolver trying to pull in 'Buffer'

```
Installing buffer...

@parcel/resolver-default: Auto installing polyfill for Node builtin module "buffer"...

  /.../node_modules/.pnpm/fabric@5.2.4/node_modules/fabric/dist/fabric.js:51:30
    50 |  */
  > 51 | fabric.isLikelyNode = typeof Buffer !== 'undefined' &&
🚨 Build failed.

@parcel/core: Failed to resolve 'buffer' from './node_modules/.pnpm/fabric@5.2.4/node_modules/fabric/dist/fabric.js'

  /.../node_modules/.pnpm/fabric@5.2.4/node_modules/fabric/dist/fabric.js:51:30
    50 |  */
  > 51 | fabric.isLikelyNode = typeof Buffer !== 'undefined' &&
  >    |                              ^^^^^^
    52 |                       typeof window === 'undefined';
    53 | 

@parcel/resolver-default: Failed to install buffer: pnpm failed to install modules

  Error: Failed to install buffer: pnpm failed to install modules
      at $32ea97b83cf5d752$var$install (/.../node_modules/.pnpm/@parcel+package-manager@2.0.0-nightly.1171_mahhrzjiewej44m3u7ph6mg4jy/node_modules/@parcel/package-manager/lib/index.js:3690:15)
      at async $b0fd219fea43bcac$export$2e2bcd8739ae039._runFn (/.../node_modules/.pnpm/@parcel+utils@2.0.0-nightly.1171/node_modules/@parcel/utils/lib/index.js:33572:13)
      at async $b0fd219fea43bcac$export$2e2bcd8739ae039._next (/.../node_modules/.pnpm/@parcel+utils@2.0.0-nightly.1171/node_modules/@parcel/utils/lib/index.js:33565:9)

 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

Even with ```
	"resolvers": [
		"parcel-resolver-ignore",
		"..."
	],
``` in package.json

And 
```	"parcelIgnore": [
		"fabric.js"
	],
-- OR 
	"parcelIgnore": [
		"buffer"
	],
-- OR
	"parcelIgnore": [
		"Buffer"
	],
```

So I found another solution,
```json
	"alias": {
		"Buffer": false,
		"buffer": false
	},
```

**Comment by VladimirMikulic** [comment]
Thanks for the update and sharing your workaround.
Closing this since it's internal bug.
